-- 여러 팀이 한 앱(한 DB)을 쓰되 팀끼리는 데이터가 전혀 보이지 않게 분리한다.
--
-- 설계 (1.0.5 검토에서 확정):
-- - 별도 Supabase 프로젝트가 아니라 단일 DB + team_id. 무료 플랜은 활성 프로젝트가 2개까지라
--   팀이 늘면 유료가 되고, 마이그레이션·백업도 팀 수만큼 반복해야 해서다.
-- - 한 사람은 한 팀 전속(profiles.team_id). 가입할 때 팀을 고른다.
-- - 개발자만 active_team_id로 "지금 보고 있는 팀"을 바꿔 다른 팀 데이터를 볼 수 있다(B안).
-- - 모든 데이터 테이블에 team_id를 두고, 기존 권한 정책은 그대로 둔 채 RESTRICTIVE 정책
--   "팀 격리"를 하나씩 더한다. RESTRICTIVE는 기존(PERMISSIVE) 정책과 AND로 묶이므로
--   "원래 볼 수 있던 것 중 우리 팀 것만" 보이게 된다.
-- - team_id의 기본값을 current_team_id()로 두어, 앱 코드는 insert할 때 팀을 몰라도 된다.
--   (이전 버전 앱이 그대로 insert해도 자기 팀으로 저장된다)

-- 1) 팀 테이블과 기존 데이터가 들어갈 기본 팀
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.teams enable row level security;
-- teams는 정책 없이 막아두고, 아래 함수(list_teams 등)로만 읽고 쓴다.

insert into public.teams (name)
select '기본팀'
where not exists (select 1 from public.teams);

-- 2) 사람의 소속 팀 / 개발자가 보고 있는 팀
alter table public.profiles add column if not exists team_id bigint references public.teams (id);
alter table public.profiles add column if not exists active_team_id bigint references public.teams (id) on delete set null;

update public.profiles
   set team_id = (select min(id) from public.teams)
 where team_id is null;

alter table public.profiles alter column team_id set not null;
create index if not exists idx_profiles_team on public.profiles (team_id);

-- 지금 로그인한 사람이 보고 있는 팀. 개발자는 전환해둔 팀(없으면 자기 팀), 그 외는 자기 팀.
-- profiles의 RLS를 거치면 정책이 이 함수를 다시 부르며 순환하므로 security definer로 직접 읽는다.
create or replace function public.current_team_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select case when p.role = '개발자' then coalesce(p.active_team_id, p.team_id) else p.team_id end
  from public.profiles p
  where p.id = auth.uid()
$$;

grant execute on function public.current_team_id() to anon, authenticated;

-- 3) 데이터 테이블마다 team_id 추가 → 기존 행은 기본 팀으로 채움 → 기본값·인덱스·팀 격리 정책
do $$
declare
  default_team bigint := (select min(id) from public.teams);
  tbl text;
  tables text[] := array[
    'sites', 'buildings', 'building_lines', 'unit_checks', 'defects', 'unit_logs',
    'site_checklist_items', 'site_receipts', 'site_members', 'site_favorites',
    'attendances', 'expenses', 'actual_salaries', 'salary_entries', 'profile_rate_history',
    'upcoming_sites', 'upcoming_visits'
  ];
begin
  foreach tbl in array tables loop
    execute format('alter table public.%I add column if not exists team_id bigint references public.teams (id)', tbl);
    execute format('update public.%I set team_id = %s where team_id is null', tbl, default_team);
    execute format('alter table public.%I alter column team_id set not null', tbl);
    execute format('alter table public.%I alter column team_id set default public.current_team_id()', tbl);
    execute format('create index if not exists %I on public.%I (team_id)', 'idx_' || tbl || '_team', tbl);
    execute format('drop policy if exists "팀 격리" on public.%I', tbl);
    -- (select ...)로 감싸면 행마다가 아니라 쿼리당 한 번만 계산된다
    execute format(
      'create policy "팀 격리" on public.%I as restrictive for all '
      'using (team_id = (select public.current_team_id())) '
      'with check (team_id = (select public.current_team_id()))',
      tbl
    );
  end loop;
end
$$;

-- profiles는 본인 행은 항상 읽고 고칠 수 있어야 한다(개발자가 다른 팀을 보고 있어도 로그인 정보는 필요).
drop policy if exists "팀 격리" on public.profiles;
create policy "팀 격리" on public.profiles
  as restrictive
  for all
  using (id = auth.uid() or team_id = (select public.current_team_id()))
  with check (id = auth.uid() or team_id = (select public.current_team_id()));

-- 4) 본인이 소속 팀/보고 있는 팀을 스스로 바꾸지 못하게 한다. (authenticated에는 이 두 컬럼의
--    UPDATE 권한도 주지 않았다. 바꾸는 길은 아래 개발자 전용 함수뿐이다)
create or replace function public.prevent_self_role_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_dev() and new.role is distinct from old.role then
    new.role := old.role;
  end if;
  if not public.is_dev() and new.is_test_account is distinct from old.is_test_account then
    new.is_test_account := old.is_test_account;
  end if;
  if not public.is_dev() and new.team_id is distinct from old.team_id then
    new.team_id := old.team_id;
  end if;
  if not public.is_dev() and new.active_team_id is distinct from old.active_team_id then
    new.active_team_id := old.active_team_id;
  end if;
  return new;
end;
$$;

-- 5) 가입 시 고른 팀으로 프로필을 만든다. 팀을 안 보냈거나(이전 버전 앱) 없는 팀이면 기본 팀.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested bigint;
  chosen bigint;
begin
  begin
    requested := nullif(trim(new.raw_user_meta_data ->> 'team_id'), '')::bigint;
  exception when others then
    requested := null;
  end;

  select t.id into chosen from public.teams t where t.id = requested;
  if chosen is null then
    select min(t.id) into chosen from public.teams t;
  end if;

  insert into public.profiles (id, name, team_id)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1)),
    chosen
  );
  return new;
end;
$$;

-- 6) RLS를 우회하는(security definer) 기존 함수들에 팀 조건을 넣는다

-- 처리자 이름: 우리 팀 사람만. 개발자는 어느 팀 기록에든 남을 수 있어 이름을 함께 돌려준다.
create or replace function public.user_names()
returns table (id uuid, name text)
language sql
stable
security definer
set search_path = ''
as $$
  select p.id, p.name
  from public.profiles p
  where p.team_id = public.current_team_id() or p.role = '개발자';
$$;

create or replace function public.set_sheet_sharing(owner_site_id bigint, site_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  keep_ids bigint[] := coalesce(site_ids, '{}');
  my_team bigint := public.current_team_id();
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not exists (select 1 from public.sites where id = owner_site_id and team_id = my_team) then
    raise exception '현장을 찾을 수 없습니다.';
  end if;

  update public.sites
     set sheet_source_id = null
   where sheet_source_id = owner_site_id
     and team_id = my_team
     and not (id = any (keep_ids));

  update public.sites
     set sheet_source_id = owner_site_id
   where id = any (keep_ids)
     and id <> owner_site_id
     and team_id = my_team;
end;
$$;

create or replace function public.update_profile_rate(
  target_user_id uuid,
  new_rate integer,
  target_year integer,
  target_month integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_manager() then
    raise exception '권한이 없습니다.';
  end if;

  if not exists (select 1 from public.profiles where id = target_user_id and team_id = public.current_team_id()) then
    raise exception '같은 팀 인원만 단가를 수정할 수 있습니다.';
  end if;

  insert into public.profile_rate_history (user_id, year, month, rate, team_id)
  values (target_user_id, target_year, target_month, new_rate, public.current_team_id())
  on conflict (user_id, year, month) do update set rate = excluded.rate, updated_at = now();

  update public.profiles set rate = new_rate where id = target_user_id;
end;
$$;

-- 7) 영수증·급여 증빙 사진: 팀장·개발자라도 우리 팀 사람의 파일만 볼 수 있다
drop policy if exists "영수증 조회" on storage.objects;
create policy "영수증 조회"
  on storage.objects
  as permissive
  for select
  to authenticated
  using (
    bucket_id = 'receipts'
    and (
      (storage.foldername(name))[1] = (auth.uid())::text
      or (
        public.is_manager()
        and exists (
          select 1 from public.profiles p
          where p.id::text = (storage.foldername(name))[1]
            and p.team_id = public.current_team_id()
        )
      )
    )
  );

-- 8) 팀 관련 함수

-- 가입 화면(로그인 전)에서도 팀을 고를 수 있어야 해서 anon에게도 연다. 팀 이름만 돌려준다.
create or replace function public.list_teams()
returns table (id bigint, name text)
language sql
stable
security definer
set search_path = ''
as $$
  select t.id, t.name from public.teams t order by t.id;
$$;

grant execute on function public.list_teams() to anon, authenticated;

create or replace function public.create_team(team_name text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if not public.is_dev() then
    raise exception '개발자만 팀을 만들 수 있습니다.';
  end if;
  if coalesce(trim(team_name), '') = '' then
    raise exception '팀 이름을 입력하세요.';
  end if;

  insert into public.teams (name) values (trim(team_name)) returning id into new_id;
  return new_id;
end;
$$;

-- 개발자가 지금 볼 팀을 바꾼다. null이면 자기 소속 팀으로 돌아간다.
create or replace function public.switch_active_team(target_team_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_dev() then
    raise exception '개발자만 팀을 전환할 수 있습니다.';
  end if;
  if target_team_id is not null and not exists (select 1 from public.teams where id = target_team_id) then
    raise exception '없는 팀입니다.';
  end if;

  update public.profiles set active_team_id = target_team_id where id = auth.uid();
end;
$$;

-- 전체 인원과 소속 팀(개발자 페이지의 팀 배정용). 팀 격리를 넘어 모든 팀을 봐야 해서 함수로만 연다.
create or replace function public.list_all_members()
returns table (id uuid, name text, role public.user_role, team_id bigint)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_dev() then
    raise exception '권한이 없습니다.';
  end if;
  return query select p.id, p.name, p.role, p.team_id from public.profiles p order by p.name;
end;
$$;

-- 가입 때 팀을 잘못 고른 사람을 옮긴다. 이미 쌓인 출근·지출 등 기록은 원래 팀에 남는다.
create or replace function public.set_user_team(target_user_id uuid, target_team_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_dev() then
    raise exception '개발자만 소속 팀을 바꿀 수 있습니다.';
  end if;
  if not exists (select 1 from public.teams where id = target_team_id) then
    raise exception '없는 팀입니다.';
  end if;

  update public.profiles set team_id = target_team_id where id = target_user_id;
end;
$$;

revoke all on function public.create_team(text) from public;
revoke all on function public.switch_active_team(bigint) from public;
revoke all on function public.list_all_members() from public;
revoke all on function public.set_user_team(uuid, bigint) from public;
grant execute on function public.create_team(text) to authenticated;
grant execute on function public.switch_active_team(bigint) to authenticated;
grant execute on function public.list_all_members() to authenticated;
grant execute on function public.set_user_team(uuid, bigint) to authenticated;
