-- 단가를 profiles.rate 하나로만 관리하면, 단가를 수정하는 순간 과거 달 급여 계산까지
-- 최신 단가로 다시 계산돼서 그 당시 값과 달라진다. 연/월별 단가 이력을 따로 두고,
-- 급여 계산은 항상 "그 달에 유효했던 단가"를 찾아 쓰도록 바꾼다.
create table public.profile_rate_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  year integer not null,
  month integer not null check (month between 1 and 12),
  rate integer not null,
  updated_at timestamptz not null default now(),
  unique (user_id, year, month)
);

alter table public.profile_rate_history enable row level security;

-- 본인 단가 이력은 본인도 볼 수 있게(급여 상세 화면에서 함께 쓰일 수 있음), 그 외엔 매니저만.
create policy "단가 이력 조회" on public.profile_rate_history
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_manager());

grant select on public.profile_rate_history to authenticated;
grant select, usage on sequence public.profile_rate_history_id_seq to authenticated;
-- insert/update/delete는 authenticated에 주지 않는다. 쓰기는 아래 RPC로만 한다.

-- 이 기능이 생기기 전 단가는 기록이 없으니, 지금 profiles.rate 값이 아주 예전부터
-- 계속 적용돼온 것으로 간주해 이른 날짜로 한 행씩 백필한다(최선의 근사치).
insert into public.profile_rate_history (user_id, year, month, rate)
select id, 2000, 1, rate from public.profiles;

-- 단가 수정 RPC가 적용 연/월을 받아서 이력에 upsert하도록 재정의. 같은 달에 다시
-- 고치면 그 값으로 덮어쓴다(이력을 겹겹이 쌓지 않음 — 그 달 단가는 하나만 있으면 됨).
drop function if exists public.update_profile_rate(uuid, integer);

create or replace function public.update_profile_rate(
  target_user_id uuid,
  new_rate integer,
  target_year integer,
  target_month integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_manager() then
    raise exception '권한이 없습니다.';
  end if;

  insert into public.profile_rate_history (user_id, year, month, rate)
  values (target_user_id, target_year, target_month, new_rate)
  on conflict (user_id, year, month) do update set rate = excluded.rate, updated_at = now();

  -- profiles.rate는 "가장 최근 입력값" 캐시로 계속 유지한다(연/월 맥락 없는 곳의 참고용).
  update public.profiles set rate = new_rate where id = target_user_id;
end;
$$;

revoke all on function public.update_profile_rate(uuid, integer, integer, integer) from public;
grant execute on function public.update_profile_rate(uuid, integer, integer, integer) to authenticated;
