-- 현장 상세에 체크리스트 탭을 추가한다. 자유 텍스트 항목 + 체크박스, 마지막으로
-- 체크한 사람/시간을 unit_checks의 light_by/light_at 관례를 따라 남긴다.
create table if not exists public.site_checklist_items (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  content text not null default '',
  checked boolean not null default false,
  checked_by uuid references public.profiles (id),
  checked_at timestamptz,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_site_checklist_items_site
  on public.site_checklist_items (site_id, created_at);

alter table public.site_checklist_items enable row level security;

-- 세대표·미타공과 동일하게, 로그인한 팀원이면 누구나 조회·작성·체크할 수 있다.
create policy "체크리스트 관리" on public.site_checklist_items
  using (auth.uid() is not null);

grant select, insert, update, delete on public.site_checklist_items to authenticated;
grant select, usage on sequence public.site_checklist_items_id_seq to authenticated;
