-- 개인 > 급여: 본인이 받은 급여를 "일한 달 · 현장" 단위로 직접 입력하고 증빙 사진을 남긴다.
--
-- 기존 actual_salaries는 (user_id, year, month) 유니크에 팀장·개발자만 입력할 수 있는 구조라
-- "한 달에 현장별로 여러 건, 본인이 입력"을 담을 수 없다. 새 테이블을 두고, 사람·달 단위로
-- 합산한 값을 실급여로 쓴다(인건비 탭·인건비 상세·개인 대시보드). site_id가 생기면서
-- 결제 > 현장 상세의 실급여도 그 현장에서 받은 금액만으로 정확히 나눠진다.
create table if not exists public.salary_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  -- 현장은 삭제해도 보관(archived_at)만 되므로 실제로 지워질 일은 거의 없지만, 지워져도 금액 기록은 남긴다.
  -- 기존 actual_salaries에서 옮겨온 행은 어느 현장 급여인지 알 수 없어 null이다.
  site_id bigint references public.sites (id) on delete set null,
  year integer not null,
  month integer not null check (month between 1 and 12),
  amount bigint not null default 0 check (amount >= 0),
  receipt_path text,
  client_id uuid,
  created_at timestamptz not null default now()
);

create unique index if not exists salary_entries_client_id_key on public.salary_entries (client_id);
create index if not exists idx_salary_entries_user_month on public.salary_entries (user_id, year, month);
create index if not exists idx_salary_entries_site_month on public.salary_entries (site_id, year, month);

alter table public.salary_entries enable row level security;

-- 조회: 본인 것 + 팀장·개발자는 전체(인건비 탭·현장 상세에서 합산해야 함)
create policy "급여 조회" on public.salary_entries
  for select to authenticated
  using (user_id = auth.uid() or public.is_manager());

-- 입력·수정·삭제: 본인 것만. 팀장이 대신 입력하던 인건비 상세의 입력 기능은 없앤다.
create policy "급여 입력" on public.salary_entries
  for insert to authenticated
  with check (user_id = auth.uid());

create policy "급여 수정" on public.salary_entries
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "급여 삭제" on public.salary_entries
  for delete to authenticated
  using (user_id = auth.uid());

grant select, insert, update, delete on public.salary_entries to authenticated;
grant select, usage on sequence public.salary_entries_id_seq to authenticated;

-- 지금까지 팀장이 입력해둔 실급여를 그대로 옮겨서, 배포 직후 화면에서 과거 실급여가 0으로
-- 사라져 보이지 않게 한다. actual_salaries 테이블은 되돌릴 때를 대비해 지우지 않고 남겨둔다.
-- (이 마이그레이션은 1.0.5 프론트를 배포하기 직전에 push해야, 그 사이 옛 화면에서 입력된
-- 실급여가 빠지지 않는다.)
insert into public.salary_entries (user_id, site_id, year, month, amount)
select a.user_id, null, a.year, a.month, a.amount
from public.actual_salaries a
where a.amount <> 0
  and not exists (
    select 1 from public.salary_entries s
    where s.user_id = a.user_id and s.year = a.year and s.month = a.month and s.site_id is null
  );
