-- 세대별 작업 이력 테이블.
-- unit_checks/defects는 "현재 상태"만 담고 있어서(체크 여부, 마지막 처리자),
-- 체크 해제·체크 취소처럼 상태가 사라지는 동작까지 포함한 전체 이력은 남지 않는다.
create table if not exists public.unit_logs (
  id bigint generated by default as identity primary key,
  building_id bigint not null references public.buildings (id) on delete cascade,
  line_no integer not null,
  floor integer not null,
  sheet public.sheet_type not null default 'main',
  action text not null,
  detail text,
  actor_id uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_unit_logs_cell
  on public.unit_logs (building_id, line_no, floor, sheet, created_at desc);

alter table public.unit_logs enable row level security;

-- 세대표(unit_checks)·미타공(defects)과 동일하게 로그인한 사용자면 조회·등록 가능.
-- 이력이므로 수정·삭제 정책은 두지 않는다.
drop policy if exists "작업 로그 조회" on public.unit_logs;
create policy "작업 로그 조회" on public.unit_logs
  for select to authenticated
  using (auth.uid() is not null);

drop policy if exists "작업 로그 등록" on public.unit_logs;
create policy "작업 로그 등록" on public.unit_logs
  for insert to authenticated
  with check (auth.uid() is not null);

grant select, insert on public.unit_logs to authenticated;

-- 작업 이력과 체크 기록에 처리자 이름을 보여주려면 팀원도 다른 사용자의 이름을 읽을 수 있어야 한다.
-- profiles 행 전체를 열면 전화번호·단가까지 노출되므로 이름만 돌려주는 함수로 제한한다.
create or replace function public.user_names()
returns table (id uuid, name text)
language sql
security definer
set search_path = ''
as $$
  select p.id, p.name from public.profiles p;
$$;

grant execute on function public.user_names() to authenticated;
